### ISSUE TITLE
Responsive header

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/cafeteria#19]
On a small or medium screen, the username should appear next to the user's picture not below it, and also it will look better if it was the first item in the list.

![Screenshot from 2020-11-17 01-15-34](https://user-images.githubusercontent.com/23726675/99319777-d7fd0c00-2872-11eb-8a35-64b1e26465cd.png)

**Comment by marwagado** [comment]
ok

**Comment by marwagado** [comment]
done
