### ISSUE TITLE
Responsive all categories page

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/cafeteria#20]
The `allcategories.php` page is not responsive enough. The table has a huge left margin and looks awkward.

The table should fill the whole screen on small screens.

![localhost_63342_cafeteria_views_admin_category_allcategories php all panes 2020-11-16 23 29 08](https://user-images.githubusercontent.com/23726675/99321086-b6515400-2875-11eb-85ee-6e548e81c3b5.png)

**Comment by Khalid-Abed** [comment]
Done

**Comment by Hossam-Tarek** [comment]
Well done, now it looks better.

![localhost_63342_cafeteria_views_admin_category_allcategories php# all panes 2020-11-17 07 06 58](https://user-images.githubusercontent.com/23726675/99357398-81182680-28b4-11eb-8410-0d213662eca6.png)
